geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
	path('edit/', authapp.edit, name='edit'),
]     

def register(request):
    title = 'регистрация'
    
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
    
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()
    
    content = {'title': title, 'register_form': register_form}
    
    return render(request, 'authapp/register.html', content)

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminka/', include('adminapp.urls', namespace='adminka'))
]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

from .views import (
    index, contacts, about
)


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),]
'''
urlpatterns = [
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
]
'''

geekshop/products/urls.py
from django.urls import path

from .views import (
    product_list, product_detail
)


app_name = 'products'


urlpatterns = [
    path('<int:pk>/', product_detail, name='detail'),
    path('', product_list, name='index'),
]

geekshop/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product

class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

@property
def product_cost(self):
    "return cost of all products this type"
    return self.product.price * self.quantity

@property
def total_quantity(self):
    "return total quantity for user"
    _items = Basket.objects.filter(user=self.user)
    _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
    return _totalquantity

@property
def total_cost(self):
    "return total cost for user"
    _items = Basket.objects.filter(user=self.user)
    _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
    return _totalcost

geekshop/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.contrib.auth.decorators import login_required
from django.urls import reverse


@login_required
def basket(request):
    title = 'корзина'  
    basket_items = Basket.objects.filter(user=request.user).\
                                  order_by('product__category')
    
    content = {
        'title': title,
        'basket_items': basket_items,
    }
    
    return render(request, 'basketapp/basket.html', content)

@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

geekshop/basketapp/templates/basketapp/includes/inc_basket_list.html
{% for item in basket_items %}
    <div class="basket_record">
        <img src="/media/{{ item.product.image }}" 
             alt="{{ item.product.short_desc }}">
        <span class="category_name">{{ item.product.category.name }}</span> 
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbspруб</span>
        <input type="number" name="{{ item.pk }}" min="0" 
                             value="{{ item.quantity }}">
        <span class="product_cost">{{ item.cost }}&nbspруб</span>
        <button class="btn btn-round">
            <a href="{% url 'basket:remove' item.pk %}" class="">
                удалить
            </a>
        </button>
    </div>
{% endfor %}

{% if basket_items %}
    <div class="basket_summary">
        В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
        {{ basket_items.0.total_cost }} руб
    </div>
{% endif %}

geekshop/basketapp/templates/basketapp/includes/inc_menu.html
{% load staticfiles %}
{% csrf_token %}
<header class="page__header">
    <nav class="page__navigation">
        <ul class="navigation-list">
            <li class="navigation-list__item">
                <span class="navigation-list__item-text">
                    Главная
                </span>
                <a href="{% url 'main:index' %}" class="navigation-list__item-link">
                </a>
            </li>
            <li class="navigation-list__item">
                <span class="navigation-list__item-text">
                    Продукты
                </span>
                <a href="{% url 'products:index' %}" class="navigation-list__item-link">
                </a>
            </li>
            <li class="navigation-list__item">
                <span class="navigation-list__item-text">
                    О проекте
                </span>
                <a href="/about/" class="navigation-list__item-link">
                </a>
            </li>
            <li class="navigation-list__item">
                <span class="navigation-list__item-text">
                    Контакты
                </span>
                <a href="/contacts/" class="navigation-list__item-link">
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="navigation-list__item">
                <span class="navigation-list__item-text">
                    {{ user.first_name|default:'Пользователь' }}
                </span>
                <a href="{% url 'main:edit' %}" class="navigation-list__item-link">
                </a>
            </li>
            {% endif %}
            <li class="navigation-list__item">
                {% if user.is_authenticated %}
                <span class="navigation-list__item-text">
                    выйти
                </span>
                <a href="{% url 'main:logout' %}" class="navigation-list__item-link">
                </a>
                {% else %}
                <span class="navigation-list__item-text">
                    войти
                </span>
                <a href="{% url 'main:login' %}" class="navigation-list__item-link">
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</header>