geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
	path('edit/', authapp.edit, name='edit'),
]     

def register(request):
    title = 'регистрация'
    
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
    
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()
    
    content = {'title': title, 'register_form': register_form}
    
    return render(request, 'authapp/register.html', content)

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminka/', include('adminapp.urls', namespace='adminka'))
]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

from .views import (
    index, contacts, about
)


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),]
'''
urlpatterns = [
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
]
'''

geekshop/products/urls.py
from django.urls import path

from .views import (
    product_list, product_detail
)


app_name = 'products'


urlpatterns = [
    path('<int:pk>/', product_detail, name='detail'),
    path('', product_list, name='index'),
]

geekshop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

# Create your models here.

geekshop/products/models.py
from django.db import models

# Create your models here.

geekshop/mainapp/views.py
from django.shortcuts import render
from django.template import Template, Context
from django.utils.html import mark_safe
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from .models import ProductCategory, Product

def main(request):
    title = 'главная'
    
    products = Product.objects.all()[:4]
        
    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)

    title = 'Продукты'
    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    
    content = {
        'title': title,
        'links_menu': links_menu, 
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


# Create your views here.
def index(request):
    # CONST = False

    # template = Template('<h1>{{ variable }}</h1>')

    # if CONST:
    #     context_value = {'variable':'Hello'} 
    # else:
    #     context_value = {'variable':'World'}

    # context = Context(context_value)

    # return HttpResponse(
    #     template.render(context)
    # )
    template = get_template('mainapp/index.html')
    context = {'description': 'Главная страница Интернет-витрины'}
    return HttpResponse(
        template.render(context)
    )


def about(request):
    return HttpResponse(
        render_to_string(
            'mainapp/about.html',
            {'description': 'Информационная страница Интернет-витрины'}
        )
    )


def contacts(request):
    return render(
        request, 
        'mainapp/contacts.html',
        {
            'contacts': [
                'Контакт 1','Контакт 2','Контакт 3',
            ]
        }
    )

def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []

        
def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]
    
    
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:3]

    return same_products

def product(request, pk):
    title = 'продукты'
    
    content = {
        'title': title, 
        'links_menu': ProductCategory.objects.all(), 
        'product': get_object_or_404(Product, pk=pk), 
        'basket': get_basket(request.user),
    }
	
    return render(request, 'mainapp/product.html', content)

geekshop/products/views.py
import json
from django.shortcuts import render


# Create your views here.
def product_list(request):
    with open('products/fixtures/data.json', 'rb') as file:
        return render(
            request, 
            'products/index.html',
            {'products': json.load(file)}
        )


def product_detail(request, pk):
    with open('products/fixtures/data.json', 'rb') as file:
        return render(
            request,
            'products/detail.html',
            {'product': json.load(file)[pk]}
        )

geekshop/mainapp/templates/mainapp/about.html
{% extends 'mainapp/master.html' %}

{% block page_title %}
About page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            О проекте
        </h1>
        <div class="branding">
            <img src="" alt="" class="branding__background">
            <span class="branding__snippet">
                {{ description }}
            </span>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}   
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}
 
        {% endblock %}
        
        {% block content %}

        {% endblock %}

	</div>
    
    {% block footer %}
        <div class="footer">
            <div class="text-footer">
               <h3>контакты</h3>
            </div>
            <div class="text-footer">
               <h3>полезная информация</h3>
            </div>
        </div>
    {% endblock %}
	
</body>
</html>

geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/master.html' %}

{% block page_title %}
Contacts page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            Контакты
        </h1>
        <ul class="contacts-list">
            {% for itm in contacts %}
            <li>
                <span>
                    {{ itm }}
                </span>
            </li>
            </br>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/inc_categories_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

geekshop/mainapp/templates/mainapp/inc_menu.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% if user.is_authenticated %}
<li>
    <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}          
    </a>
</li>
{% endif %}  
<li>
    {% if user.is_authenticated %}
      <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
      <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}
</li>

<li>
  <a href="{% url 'products:index' %}"
     class="{% if request.resolver_match.namespace == 'products' %}
              active
            {% endif %}">
    продукты
  </a>
</li>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/master.html' %}

{% block page_title %}
Home page
{% endblock %}

{% block page_content %}
    <div class="page__content">
        <h1 class="page__title">
            Главная страница
        </h1>
        <div class="page__preview">
            <img src="" alt="" class="branding__background">
            <span class="branding__snippet">
                {{ description }}
            </span>
        </div>
    </div>

    {% for product in products %}
      <div class="block">
        <a href="#">
          <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}"> 
          <div class="text">
            <h3>{{ product.category.name }}</h3>        
            <h4>{{ product.name }}</h4>
            <p>{{ product.description }}</p>
          </div>
        </a>
      </div>
    {% endfor %}

            
{% endblock %}

geekshop/mainapp/templates/mainapp/master.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block page_title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/static/main/css/index.css" />
    </head>

    <body>
        <div class="page">
            <header class="page__header">
                <nav class="page__navigation">
                    <ul class="navigation-list">
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Главная
                            </span>
                            <a href="{% url 'mainapp:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Товары
                            </span>
                            <a href="{% url 'products:index' %}" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                О проекте
                            </span>
                            <a href="/about/" class="navigation-list__item-link">
                            </a>
                        </li>
                        <li class="navigation-list__item">
                            <span class="navigation-list__item-text">
                                Контакты
                            </span>
                            <a href="/contacts/" class="navigation-list__item-link">
                            </a>
                        </li>
                    </ul>
                </nav>
            </header>
            {% block page_content %}
                 
            {% endblock %}

            <h5> сегодня {% now "d.m.Y" %} </h5> 
            <footer class="page__footer">
                <span class="page__copyright">
                    © GeekBrains 
                </span>
                <span class="page__copyright_date">
                    
                </span>
            </footer>
        </div>
    </body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>«Башмачок» - Каталог</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="container">
    <div class="header">
        <div class="logo"> <img src="/static/img/bashmak.jpg"></div>
        <div class="menu">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><a href="/products/">Каталог</a></li>
                <li><a href="/contact/">Контакты</a></li>
                <!--<li><a href="registration.html">Регистрация</a></li>
                  -->
            </ul>
        </div>
    </div>
    <div class="content">
        <h1>Каталог</h1>
        <div class="product">
            <h3>Мужская обувь</h3>
            <a href="catalog/boots.html"> <img class="small" src="/static/img/small_boots.webp" alt="ботиночки"></a>
            <br> <a href="catalog/boots.html">Ботинки мужские</a> 
        </div>
        <div class="product">
            <h3>Женская обувь</h3>
            <a href="catalog/shoes.html"> <img class="small" src="/static/img/small_shoes.webp" alt="туфельки"></a>
            <br> <a href="catalog/shoes.html">Туфли женские</a> 
        </div>
        <div class="product">
            <h3>Детская обувь</h3>
            <a href="catalog/sneakers.html"> <img class="small" src="/static/img/small_sneakers.jpg" alt="кедики"></a>
            <br> <a href="catalog/sneakers.html">Кеды детские</a> 
        </div>
    </div>
    <div class="footer"> &copy;&nbsp; Все права защищены 
        <a href="https://geekbrains.ru/" target="_blank">GeekBrains</a> 2019. SVlad <sup class="reg">&reg;</sup> 
    </div>
</div>    
<div class="details-products">
    <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ hot_product.image }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
          </div>
          <div class="block">
            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
          </div>
          <div class="block">
            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ hot_product.name }}</h3>
        <h3 class="red">горячее предложение</h3>
        <p class="price">{{ hot_product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
          заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ hot_product.description }} 
        </div>
    </div>
</div>

</body>
</html>

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'mainapp/includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
      <div class="category-products clearfix">

        {% for product in products %}
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="product">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>
<div class="category-products clearfix">
  {% for product in products %}
    <div class="block">
      <a href="{% url 'basket:add' product.pk %}">
        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
        <div class="text">
          <img src="{% static 'img/icon-hover.png' %}" alt="hover">
          <h4>{{ product.name }}</h4>
          <p>{{ product.description }} </p>
        </div>
      </a>
    </div>
  {% endfor %}
</div>

{% endblock %}